#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1

#SBATCH --job-name=ass2.1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:59:00
#SBATCH --mem=32000M
#SBATCH --output=/home/scur1382/uvadlc_practicals_2023/%A.out

date

TMPDIR="/scratch-local/scur1382/"

module purge
module load 2022
module load Anaconda3/2022.05

# Your job starts in the directory where you call sbatch
WORKDIR=$HOME/uvadlc_practicals_2023
cd $WORKDIR

cp -r $WORKDIR/data/ $TMPDIR/

# Activate your environment
source activate dl2023

# pip install git+https://github.com/openai/CLIP.git

# Run 1: Zero-shot CLIP on CIFAR-10 with standard text prompt

echo "Running zero-shot CLIP on CIFAR-10 with standard text prompt"
echo "python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar10 --split test --root $TMPDIR"

python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar10 --root $TMPDIR
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar10 --split test --root $TMPDIR
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar10 --split test --root $TMPDIR --class_names red blue green --prompt_template "This is a photo of a {} object" --visualize_predictions
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar10 --split test --root $TMPDIR --class_names "man-made" "coming from nature" --prompt_template "This is a photo of a {} object" --visualize_predictions

echo "Running zero-shot CLIP on CIFAR-100 with standard text prompt"
echo "python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar100 --split test --root $TMPDIR"
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar100 --root $TMPDIR
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar100 --split test --root $TMPDIR
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar100 --split test --root $TMPDIR --class_names red blue green --prompt_template "This is a photo of a {} object" --visualize_predictions
python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar100 --split test --root $TMPDIR --class_names "man-made" "coming from nature" --prompt_template "This is a photo of a {} object" --visualize_predictions
