#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1

#SBATCH --job-name=ass2.1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:30:00
#SBATCH --mem=60000M
#SBATCH --output=/home/scur1382/uvadlc_practicals_2023/ass_2.1_slurm_%A.out

date

TMP_DIR="/scratch-local/scur1382/"

module purge
module load 2022
module load Anaconda3/2022.05

# Your job starts in the directory where you call sbatch
WORKDIR=$HOME/uvadlc_practicals_2023
cd $WORKDIR

cp -r $WORKDIR/data/ $TMP_DIR

# Activate your environment
source activate dl2023

# pip install git+https://github.com/openai/CLIP.git

# Run 1: Zero-shot CLIP on CIFAR-10 with standard text prompt

python $WORKDIR/assignment2/part2/clipzs.py --dataset cifar10 --split test --root $TMP_DIR
python $WORDIR/assignment2/part2/clipzs.py --dataset cifar100 --split test --root $TMP_DIR
